### ISSUE TITLE
More description 

### ISSUE THREAD

**Issue by ashrafalzyoud** [famiprog/redmine_advanced_messenger#18]
Thx for your plugin
Can u tell us more description?!with pics
Can u tell us what this plugin do,which version support,can work locally,can work with MySQL?!

**Comment by ashrafalzyoud** [comment]
@cristian-spiescu 
@mircea-negreanu 
@daniela-mateescu 
@daniela-buzatu

**Comment by cristian-spiescu** [comment]
Hi there :).

When we'll release a newer version, will add more doc and make it "user friendly" regarding: what it does, how to install it, etc.

**Comment by ashrafalzyoud** [comment]
Can this plugin working in local network?!
Without internet just internetwork

**Comment by cristian-spiescu** [comment]
Yes, sure.

**Comment by cristian-spiescu** [comment]
We have released a new version = v1.3.0. W/ this occasion, we have added detailed doc and screenshots.
